server:
  port: 8093
spring:
  application:
    name: cars
  data:
    mongodb:
      authentication-database: admin
      username: ${USERNAME}
      password: ${PASSWORD}
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}
  config:
    import: optional:file:.env[.properties]

kafka:
  port: ${KAFKA_HOST}:9092
  group: groupId
  topic: carsharing
  host: ${HOST}