server:
  port: 8093
spring:
  data:
  cassandra:
    keyspace-name: carsharing
    port: 9042
    local-datacenter: datacenter1
  config:
    import: optional:file:.env[.properties]

kafka:
  port: ${KAFKA_PORT}
  group: groupId
  topic: carsharing
  host: ${HOST}